all: clean links

clean:
	rm -f a.py
	rm -f b.py
	rm -f c.py
	rm -f i.py
	rm -f m
	rm -f r.py

links:
	ln -s ../Main/Agate.py      a.py
	ln -s ../Gem/Boot.py        b.py
	ln -s ../Gem/Core.py        c.py
	ln -s ../Gem/__init__.py    i.py
	ln -s Makefile              m
	ln -s ../Agate/RUNME.py     r.py
