all: clean links

clean:
	rm -f a.py
	rm -f b.py
	rm -f c.py ce.py
	rm -f e.py
	rm -f fi.py fo.py fs.py
	rm -f in.py im.py io.py
	rm -f m
	rm -f p.py
	rm -f r.py re.py

links:
	ln -s ../Main/Agate.py              a.py
	ln -s ../Gem/Boot.py                b.py
	ln -s ../Gem/Core.py                c.py
	ln -s ../Gem/CatchException.py      ce.py
	ln -s ../Gem/Exception.py           e.py
	ln -s ../Gem/File.py                fi.py
	ln -s ../Gem/FileOutput.py          fo.py
	ln -s ../Gem/FileStatus.py          fs.py
	ln -s ../Gem/__init__.py            in.py
	ln -s ../Gem/Import.py              im.py
	ln -s ../Gem/IO.py                  io.py
	ln -s Makefile                      m
	ln -s ../Gem/Path.py                p.py
	ln -s ../Agate/RUNME.py             r.py
	ln -s ../Gem/RegularExpression.py   re.py
